// Code generated by mockery v2.23.4. DO NOT EDIT.

package carts

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/tuanhuu162/go23_course/ex6/models"
)

// MockCartStorageInterface is an autogenerated mock type for the CartStorageInterface type
type MockCartStorageInterface struct {
	mock.Mock
}

type MockCartStorageInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCartStorageInterface) EXPECT() *MockCartStorageInterface_Expecter {
	return &MockCartStorageInterface_Expecter{mock: &_m.Mock}
}

// AddProductToCart provides a mock function with given fields: payload, cart
func (_m *MockCartStorageInterface) AddProductToCart(payload models.CartRequestPayload, cart *models.Cart) error {
	ret := _m.Called(payload, cart)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.CartRequestPayload, *models.Cart) error); ok {
		r0 = rf(payload, cart)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCartStorageInterface_AddProductToCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddProductToCart'
type MockCartStorageInterface_AddProductToCart_Call struct {
	*mock.Call
}

// AddProductToCart is a helper method to define mock.On call
//   - payload models.CartRequestPayload
//   - cart *models.Cart
func (_e *MockCartStorageInterface_Expecter) AddProductToCart(payload interface{}, cart interface{}) *MockCartStorageInterface_AddProductToCart_Call {
	return &MockCartStorageInterface_AddProductToCart_Call{Call: _e.mock.On("AddProductToCart", payload, cart)}
}

func (_c *MockCartStorageInterface_AddProductToCart_Call) Run(run func(payload models.CartRequestPayload, cart *models.Cart)) *MockCartStorageInterface_AddProductToCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.CartRequestPayload), args[1].(*models.Cart))
	})
	return _c
}

func (_c *MockCartStorageInterface_AddProductToCart_Call) Return(_a0 error) *MockCartStorageInterface_AddProductToCart_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCartStorageInterface_AddProductToCart_Call) RunAndReturn(run func(models.CartRequestPayload, *models.Cart) error) *MockCartStorageInterface_AddProductToCart_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProductFromCart provides a mock function with given fields: payload, cart
func (_m *MockCartStorageInterface) DeleteProductFromCart(payload models.CartRequestPayload, cart *models.Cart) error {
	ret := _m.Called(payload, cart)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.CartRequestPayload, *models.Cart) error); ok {
		r0 = rf(payload, cart)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCartStorageInterface_DeleteProductFromCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProductFromCart'
type MockCartStorageInterface_DeleteProductFromCart_Call struct {
	*mock.Call
}

// DeleteProductFromCart is a helper method to define mock.On call
//   - payload models.CartRequestPayload
//   - cart *models.Cart
func (_e *MockCartStorageInterface_Expecter) DeleteProductFromCart(payload interface{}, cart interface{}) *MockCartStorageInterface_DeleteProductFromCart_Call {
	return &MockCartStorageInterface_DeleteProductFromCart_Call{Call: _e.mock.On("DeleteProductFromCart", payload, cart)}
}

func (_c *MockCartStorageInterface_DeleteProductFromCart_Call) Run(run func(payload models.CartRequestPayload, cart *models.Cart)) *MockCartStorageInterface_DeleteProductFromCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.CartRequestPayload), args[1].(*models.Cart))
	})
	return _c
}

func (_c *MockCartStorageInterface_DeleteProductFromCart_Call) Return(_a0 error) *MockCartStorageInterface_DeleteProductFromCart_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCartStorageInterface_DeleteProductFromCart_Call) RunAndReturn(run func(models.CartRequestPayload, *models.Cart) error) *MockCartStorageInterface_DeleteProductFromCart_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCartStorageInterface creates a new instance of MockCartStorageInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCartStorageInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCartStorageInterface {
	mock := &MockCartStorageInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
