definitions:
  models.Cart:
    properties:
      items:
        additionalProperties:
          $ref: '#/definitions/models.Item'
        type: object
      total:
        type: integer
    type: object
  models.CartRequestPayload:
    properties:
      product_id:
        type: integer
      quantity:
        type: integer
    type: object
  models.Item:
    properties:
      product_id:
        type: integer
      product_name:
        type: string
      quantity:
        type: integer
    type: object
  models.Product:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: integer
      updatedAt:
        type: string
    type: object
  models.ProductSerializer:
    properties:
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: integer
      updated_at:
        type: string
    type: object
info:
  contact: {}
paths:
  /cart/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: CartRequestPayload
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.CartRequestPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Cart'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Add product to cart
      tags:
      - cart
  /cart/checkout:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Cart'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Checkout cart
      tags:
      - cart
  /cart/remove:
    delete:
      consumes:
      - application/json
      parameters:
      - description: CartRequestPayload
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.CartRequestPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Cart'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Delete product from cart
      tags:
      - cart
  /products/:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.ProductSerializer'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Show all Product we have
      tags:
      - products
    post:
      consumes:
      - application/json
      parameters:
      - description: Product
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create product with name and price
      tags:
      - products
    put:
      consumes:
      - application/json
      parameters:
      - description: Product
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Update product with id
      tags:
      - products
  /products/{product_id}:
    delete:
      parameters:
      - description: Product ID
        in: path
        name: product_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Delete product with id
      tags:
      - products
swagger: "2.0"
